### ISSUE TITLE
getJobUrl returns promise with selenium@^3.0.0 

### ISSUE THREAD

**Issue by kweiberth** [gkushang/nemo-saucelabs#8]
I've been working on upgrading to `nemo@3.0.0-alpha.6` in our project. `nemo@^3.0.0` pulls in `selenium@^3.0.0`. I've found that the `getJobUrl` method is not working properly anymore. A promise is returned on this line https://github.com/gkushang/nemo-saucelabs/blob/develop/lib/saucelabs.js#L88 and also some of the properties and nesting structure seems a little different.

Should we start a `3.x` branch with a `peerDep` of `nemo@^3.0.0` and make sure all methods still work?

**Comment by kweiberth** [comment]
I've opened a PR with some changes that make this plugin compatible with `nemo@3.0.0`: https://github.com/gkushang/nemo-saucelabs/pull/9

**Comment by gkushang** [comment]
@kweiberth thanks for making those changes. PR is merged. Could you please let me know if those changes work fine? If so, will publish as V3.

**Comment by kweiberth** [comment]
Yes, I will test thoroughly tomorrow and let you know.
